
name: Create Issues

on: 
  release:
    types: [created]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Fetch Issues from repository
      shell: bash
      run: |
        pip install -r requirements.txt
        python main.py
        git config --global user.name 'oleksis'
        git config --global user.email 'oleksis.fraga@gmail.com'
        git add .
        git commit --allow-empty -am "Update workflow"
        git push origin HEAD:master

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Create Sklearn model"
        content-filepath: "./issues/issue_1.md"
        labels: Machine Learning Models
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Neural Style Transfer with OpenCV"
        content-filepath: "./issues/issue_2.md"
        labels: Computer Vision, OpenCV
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "The Unreasonable Effectiveness of Recurrent Neural Networks"
        content-filepath: "./issues/issue_3.md"
        labels: NLP
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Stacking Ensemble Machine Learning With Python"
        content-filepath: "./issues/issue_4.md"
        labels: Machine Learning Models
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Good coding practices for Data Science"
        content-filepath: "./issues/issue_5.md"
        labels: Data Science Tips
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Learning Git: 5 Shortcuts to Improve Your Coding Speed"
        content-filepath: "./issues/issue_6.md"
        labels: Version Control
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Version Control for Data Science — Tracking Machine Learning models and datasets"
        content-filepath: "./issues/issue_7.md"
        labels: Data Science Tools, Version Control
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Build an app to generate photorealistic faces using TensorFlow and Streamlit"
        content-filepath: "./issues/issue_8.md"
        labels: Machine Learning Deployment, Streamlit, TensorFlow
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Scraping Flight Data Using Python"
        content-filepath: "./issues/issue_9.md"
        labels: Web Scraping
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "A Visual and Interactive Guide to the Basics of Neural Networks"
        content-filepath: "./issues/issue_10.md"
        labels: Data Visualization, Neural Network
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Jupyter Superpower — Interactive Visualization Combo with Python"
        content-filepath: "./issues/issue_11.md"
        labels: Data Visualization, Jupyter Notebook
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Tokenization and Text Data Preparation with TensorFlow & Keras"
        content-filepath: "./issues/issue_12.md"
        labels: NLP, TensorFlow
        project: Machine Learning Articles
        project-column: To do
