
name: Create Issues

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Run main.py and Copy new Workflow 
      shell: bash
      run: |
        pip install -r requirements.txt
        python main.py
        cp -f ciff.yml .github/workflows/
        git config --global user.name 'oleksis'
        git config --global user.email 'oleksis.fraga@gmail.com'
        git add .
        git commit --allow-empty -am "Update workflow"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_SECRET }}


    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Object-oriented programming for data scientists: Build your ML estimator"
        content-filepath: "./issues/issue_25.md"
        labels: Data Science Tips, Python
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Top 10 Magic Commands in Python to Boost your Productivity"
        content-filepath: "./issues/issue_24.md"
        labels: Data Science Tools, Jupyter Notebook
        project: Machine Learning Articles
        project-column: To do
