
name: Create Issues

on: 
  release:
    types: [created]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Delete issues
      shell: bash
      run: |
        rm -rf issues/issue_*.md
        git config --global user.name 'oleksis'
        git config --global user.email 'oleksis.fraga@gmail.com'
        git add .
        git commit --allow-empty -am "Update workflow"
        git push origin HEAD:master
