
name: Create Issues

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Run main.py and Copy new Workflow 
      shell: bash
      run: |
        pip install -r requirements.txt
        python build/main.py
        cp -f ciff.yml .github/workflows/
        rm -f ciff.yml
        git config --global user.name 'oleksis'
        git config --global user.email 'oleksis.fraga@gmail.com'
        git add .
        git commit --allow-empty -am "Update workflow"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_SECRET }}


    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "Understanding emotions - from Keras to pyTorch"
        content-filepath: "./build/issues/issue_27.md"
        labels: 
        project: Machine Learning Articles
        project-column: To do
