name: Create Issues

on: 
  release:
    types: [created]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Fetch Issues from repository
      shell: bash
      run: |
        pip install -r requirements.txt
        python main.py
        git config --global user.name 'oleksis'
        git config --global user.email 'oleksis.fraga@gmail.com'
        git add .
        git commit --allow-empty -am "Update workflow"
        git push origin HEAD:master

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "How to Use MLflow To Reproduce Results and Retrain Saved Keras ML Models"
        content-filepath: "./issues/issue_16.md"
        labels: Data Science Tools, Machine Learning Models
        project: Machine Learning Articles
        project-column: To do

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "4 Types of Classification Tasks in Machine Learning"
        content-filepath: "./issues/issue_15.md"
        labels: Machine Learning Models
        project: Machine Learning Articles
        project-column: To do
